---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/cluster_services/kubernetes-secret-generator
  - ../../apps/cluster_services/nginx-ingress
  - ../../apps/cluster_services/chart-museum
  - ./chart-museum-secret.yaml
patchesStrategicMerge:
  - ./values.yaml
