# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chart-museum
resources:
  - repository.yaml
  - namespace.yaml
  - release.yaml
