# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chart-museum
spec:
  # Default values
  # https://github.com/chartmuseum/charts/blob/main/src/chartmuseum/values.yaml
  releaseName: chart-museum
  chart:
    spec:
      chart: chartmuseum
      sourceRef:
        kind: HelmRepository
        name: chart-museum
        namespace: chart-museum
      version: "3.1.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
