apiVersion: v1
data:
    password: ENC[AES256_GCM,data:IZ+zddh30pMCwSY2YuUmkN9e6N4=,iv:qUoXysqgVY6A1pVBrCI9xinQz8TTZBG3lrgYe0fG+h4=,tag:tOug4AVfES7+VcqPlPcrWA==,type:str]
    user: ENC[AES256_GCM,data:OmCb7NwpwDc=,iv:El4DNhDSYjwE198KQzFzWLjM+84PpHf0fG2px6SLLdg=,tag:OZmrhouazWDqseUPQ+XLhg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-21T20:00:34Z"
    mac: ENC[AES256_GCM,data:VkTyGJ/v7+h017uRVGSPW3A68fOnbYbK405cfoUTJMA1oYoYiNSKrmV2HKv8GVRgfAXLd8KWWE2yfyNDSG0V/D61RSwZyS/XvdE5T9jr4AotbkDGavw8wlpJU036EKdT+ZVhJYaIDMEoCwS3Ts9RzDVdLN+puZ/RLsuZlrg1cRo=,iv:qRr47dClNX3bfd51bXg8v9Yk7GSIV/cwACbiEzK2kCQ=,tag:OlCU7MeS/u4Wd9cTfsrnEA==,type:str]
    pgp:
        - created_at: "2021-08-21T20:00:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5KoXmFIKJSsARAAkL53L/nGlVSMEVXfe3cFtMj75sUwxhtlBNKsNTpvi81L
            wLDvw9CedxRDHHnWT3+sxCqoyoleQSqU3s1VoBAhwHtaMAB5TPvExcTM/kvTfIKe
            UaV09QPjIp/ryzV5J8T8G0UDzGl8SPM3IgMtCyAXjUp7YJART4VH2yZ+4RSiDRFs
            5U5mnutx2UJDfYH/zxuubQuCbQkBiHvlv+8CBxW3LjTPbIDNO6a0TIL3ZYKWbfLP
            KhMY34IIykZanUXVYpUKUmTgNkTrAf3OPpo+cpXANnIfmdqJr5w4JFUVK67lif7L
            Vy/H9RyBELBB3Q9wR49BA7jHOSiD2GgE8Y6tcpZSkxLnmJklfpHEAK8hnajajoRN
            pZTwzAeWXbA+/FLVw/rOvOmzZyKYKpbsMy5BX0N8pFlu8QA4PUHe2XyLkJ2PlmIc
            BIIJbdhJQX1GFHCXsOvCKQsHuRgnEAWrTUvRaWqAOJs3h6wfh0VpptIU+GoSY73S
            pqAtDgmblqFAZKiUb6YXyuDl6EBZY2d0i1jSmjr+kVZAcQu/oQo/l8e+PZvBLZ5N
            LY3ylGuPmAWFS3B8nz9/XO/EgRleVOgAFQvAgkgBbKrgGzk29zRfAjrIRt4oZGjW
            g7WS8w0z0pAHq+AAUixNNzDZyCsZLb9Cm3/2M/1Tgi/Pqv3stM8tBogswxmq7LPS
            XAGv+aNJqAeimf2HX6ApONlNdwgm+8Tx1p1GT8qH600XAszX807zlDaaplXNqhJj
            xD6MOrkvCqfWRuQqQ/AM74yFJ6cnMkfg57Nll5a0T2L/HKMLUDaL4cGduBio
            =Qr5u
            -----END PGP MESSAGE-----
          fp: F4555DF194EBFEFB93C1FD18EFDD609D4E506D53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
